using System.Collections.Generic;

namespace IntoTheVoidServer.Router;

public static class RouteMap
{
    public static readonly Dictionary<string, string> Routes = new()
    {
        ["1"] = "BackPackListResponse",
        ["2"] = "EntryResponse",
        ["3"] = "SetCurrentSquadResponse",
        ["4"] = "AddBackItemResponse",
        ["5"] = "BagItemProcessResponse",
        ["6"] = "PlayerDataResponse",
        ["gate.CurrencyDataPush"] = "CurrencyPushResponse",
        ["8"] = "ChangeWeaponResponse",
        ["9"] = "CharacterSquadInfoResponse",
        ["10"] = "ChangeSquadResponse",
        ["11"] = "ItemLockResponse",
        ["13"] = "CityNodeInfosResponse",
        ["14"] = "SettleDataResponse",
        ["15"] = "ModLvUpResponse",
        ["16"] = "ModChangeResponse",
        ["17"] = "ModUnloadResponse",
        ["18"] = "CheatUnlockCityResponse",
        ["19"] = "UseBackItemResponse",
        ["20"] = "QuestListResponse",
        ["gate.QuestPushResponse"] = "QuestPushResponse",
        ["22"] = "QuestRewardResponse",
        ["gate.QuestRefreshPushResponse"] = "QuestRefreshPushResponse",
        ["24"] = "ShopBuyResponse",
        ["gate.ShopRefreshPushResponse"] = "ShopRefreshPushResponse",
        ["26"] = "PlayerCheckResponse",
        ["27"] = "BattleQuestRewardResponse",
        ["28"] = "ExaminationReadyTimestampResponse",
        ["29"] = "ExaminationSettleResponse",
        ["30"] = "CheatAddMRResponse",
        ["31"] = "CraftResponse",
        ["32"] = "CraftListResponse",
        ["33"] = "CraftAccelerateResponse",
        ["34"] = "CheatAddEquipmentExpResponse",
        ["35"] = "CraftCancelResponse",
        ["36"] = "CraftClaimResponse",
        ["37"] = "CheatPlayerLvUpResponse",
        ["38"] = "CheatGraduateResponse",
        ["42"] = "UseRewardChestItemResponse",
        ["43"] = "CheatAddRewardChestResponse",
        ["44"] = "SetQuestStepsResponse",
        ["45"] = "CheatSetQuestResponse",
        ["46"] = "ChooseQuestRewardResponse",
        ["47"] = "GetCurrentShowCharacterResponse",
        ["48"] = "SetCurrentShowCharacterResponse",
        ["55"] = "MailFetchResponse",
        ["56"] = "MailReadResponse",
        ["57"] = "MailReceiveResponse",
        ["58"] = "MailDeleteResponse",
        ["63"] = "SearchUserResponse",
        ["64"] = "GetFriendListResponse",
        ["65"] = "AddFriendResponse",
        ["66"] = "AcceptFriendResponse",
        ["73"] = "ShopInfoResponse",
        ["75"] = "CheatSetSliceResponse",
        ["77"] = "ReceiveQuestRewardResponse",
        ["78"] = "GetProfileResponse",
        ["79"] = "SetProfileCharacterResponse",
        ["80"] = "SetAvatarResponse",
        ["81"] = "SetNicknameResponse",
        ["88"] = "CheatCleanBagResponse",
        ["89"] = "CheatClearShopBuyInfoResponse",
        ["90"] = "CheatCompleteBountyResponse",
        ["92"] = "CheatFullRankAllModResponse",
        ["94"] = "CheatPaymentFinishResponse",
        ["98"] = "CheatUnlockPackResponse",
        ["100"] = "CheatUnlockAllEnemyResponse",
        ["101"] = "CheatStalkerWeightSetResponse",
        ["102"] = "CheatTreeOpenResponse",
        ["103"] = "CheatGuildResearchResponse",
        ["110"] = "LevelBeginResponse",
        ["112"] = "LevelResourceResponse",
        ["113"] = "LevelEnemyDropResponse",
        ["114"] = "CreateSceneRoomResponse",
        ["115"] = "EnterSceneRoomResponse",
        ["117"] = "GetSceneRoomListResponse",
        ["119"] = "SceneMoveResponse",
        ["124"] = "ItemDropWorldPoolResponse",
        ["126"] = "ReceiveDropWorldPoolResponse",
        ["130"] = "GMTeamEnterLevelResponse",
        ["131"] = "MatchTeamEnterLevelResponse",
        ["132"] = "SettleDataReq",
        ["134"] = "GetSettleDataResponse",
        ["135"] = "GetTempSettleDataResponse",
        ["136"] = "ReceiveSettleDataResponse",
        ["137"] = "GetRogueSettleDataResponse",
        ["138"] = "ReceiveRogueSettleDataResponse",
        ["150"] = "PetIncubationResponse",
        ["160"] = "CreateGuildResponse",
        ["161"] = "LoadGuildInfoResponse",
        ["180"] = "CreatePaymentResponse",
        ["181"] = "CheatPaymentFinishResponse",
        ["190"] = "RogueAllInfoResponse",
        ["191"] = "RogueBattleBeginResponse",
        ["192"] = "RogueGetLevelRewardResponse",
        ["193"] = "RogueSettleResponse",
        ["200"] = "TalentTreeInfoResponse",
        ["201"] = "UnlockTalentResponse",
        ["210"] = "ScienceTreeInfoResponse",
        ["211"] = "ScienceTreeActiveNodeResponse",
        ["220"] = "ReputationTaskInfoResponse",
        ["221"] = "ReputationTaskRewardResponse",
        ["230"] = "AcquireSessionTicketResponse",
        ["231"] = "EntryResponse",
        ["232"] = "LoginDeviceInfoResponse",
        ["233"] = "LoginDevicePickResponse",
        ["234"] = "LogOffResponse",
        ["235"] = "PlayerLogoutResponse",
        ["240"] = "ChangeFrameSkinResponse",
        ["241"] = "CharacterRareUpResponse",
        ["250"] = "CheatAddBountyResponse",
        ["251"] = "CheatAddLostMailResponse",
        ["252"] = "CheatAddWellingPointsResponse",
        ["253"] = "CheatChangeUserCampResponse",
        ["254"] = "CheatFrameSkillAndWeaponSlotResponse",
        ["255"] = "CheatGetAllShownModResponse",
        ["256"] = "CheatPolarizationResponse",
        ["257"] = "CheatQuestShowMultiResponse",
        ["258"] = "CheatRoadSRankBreakResponse",
        ["259"] = "CheatRogueOutInfoResponse",
        ["260"] = "CheatSearchPointResponse",
        ["261"] = "CheatSetBackFlagResponse",
        ["262"] = "CheatSetMileScoreResponse",
        ["263"] = "CheatSignInResponse",
        ["264"] = "CheatTransformNormalResponse",
        ["265"] = "CheatWildOfferResponse",
        ["266"] = "GMPetUpRankResponse",
        ["267"] = "GMAddGuildPointResponse",
        ["268"] = "GMGuildRepairResponse",
    };

    public static string? GetMessageName(string route)
    {
        return Routes.TryGetValue(route, out var name) ? name : null;
    }
}
